stages:
  - package
  - build
  - deploy

# 正式环境
package-master:
  image: node:9.4.0
  stage: package
  script:
    - echo "正式环境"
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build:prod
    - cp Dockerfile dist/Dockerfile
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - dist/
      - node_modules/
  artifacts:
    paths:
      - dist
  only:
    - master
  tags:
    - webrunnerprod
build-master:
  stage: build
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - dist/
  script:
    - cd dist
    - docker build -t 39.102.64.21:8080/${CI_PROJECT_NAME}:${CI_PIPELINE_ID} .
    - docker push 39.102.64.21:8080/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
  only:
    - master
  tags:
    - webrunnerprod
deploy-master:
  stage: deploy
  script:
    - docker stop ${CI_PROJECT_NAME} && docker rm ${CI_PROJECT_NAME}
    - docker run -d -p 4481:80 --restart=always --name=${CI_PROJECT_NAME} 39.102.64.21:8080/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
  only:
    - master
  tags:
    - webrunnerprod
# 测试环境
package-test:
  image: node:9.4.0
  stage: package
  script:
    - echo "测试环境"
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build:stage
    - cp Dockerfile dist/Dockerfile
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
  only:
    - test
  tags:
    - webrunnerbigtest
build-test:
  stage: build
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - dist/
  script:
    - cd dist
    - docker build -t ${CI_PROJECT_NAME}:${CI_PIPELINE_ID} .
  only:
    - test
  tags:
    - webrunnerbigtest
deploy-test:
  stage: deploy
  script:
    - docker stop ${CI_PROJECT_NAME} && docker rm ${CI_PROJECT_NAME}
    - docker run -d -p 4481:80 --restart=always --name=${CI_PROJECT_NAME} ${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
    - echo "删除无用镜像"
    - docker image prune -af --filter label=^/bigscreen
  only:
    - test
  tags:
    - webrunnerbigtest

# 开发环境
package-dev:
  image: node:9.4.0
  stage: package
  script:
    - echo "开发环境"
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build:pre
    - cp Dockerfile dist/Dockerfile
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
  only:
    - dev
  tags:
    - webrunnerbig
build-dev:
  stage: build
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - dist/
  script:
    - cd dist
    - docker build -t ${CI_PROJECT_NAME}:${CI_PIPELINE_ID} .
  only:
    - dev
  tags:
    - webrunnerbig
deploy-dev:
  stage: deploy
  script:
    - docker stop ${CI_PROJECT_NAME} && docker rm ${CI_PROJECT_NAME}
    - docker run -d -p 4481:80 --restart=always --name=${CI_PROJECT_NAME} ${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
    - echo "删除无用镜像"
    - docker image prune -af --filter label=^/bigscreen
  only:
    - dev
  tags:
    - webrunnerbig
