export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: '登录',
        path: '/user/login',
        component: './user/Login',
      },
      {
        component: './404',
      },
    ],
  },
  {
    path: '/welcome',
    name: '工作台',
    icon: 'LaptopOutlined',
    access: '/dashboard/analysis',
    component: './Welcome',
  },
  {
    path: '/system/tenant',
    name: '租户管理',
    icon: 'ContainerOutlined',
    access: '/ticket/tenant',
    component: './system/tenant',
  },
  {
    path: '/customer',
    name: '客户管理',
    icon: 'user',
    access: '/ticket/client',
    component: './customer',
  },
  {
    path: '/enterprise',
    name: '企业管理',
    icon: 'user',
    access: '/ticket/enterprise',
    component: './customer/enterprise',
  },
  {
    path: '/foreign',
    name: '外商管理',
    icon: 'ContainerOutlined',
    access: '/ticket/foreign',
    component: './foreign',
  },
  {
    path: '/customer/edit',
    name: '编辑客户',
    icon: 'user',
    component: './customer/edit',
    hideInMenu: true,
  },
  {
    path: '/customer/add',
    name: '新增客户',
    icon: 'user',
    component: './customer/edit',
    hideInMenu: true,
  },
  {
    path: '/order',
    name: '订单管理',
    icon: 'FolderOpenOutlined',
    access: '/ticket/order',
    hideChildrenInMenu: true,
    routes: [
      {
        path: '/order',
        name: '订单管理',
        icon: 'smile',
        component: './order',
      },
      {
        path: '/order/info',
        name: '订单详情',
        icon: 'smile',
        component: './order/info',
      },
    ],
  },
  {
    path: '/statistics',
    name: '数据统计',
    icon: 'LineChartOutlined',
    access: '/statistics',
    component: './statistics',
  },
  // {
  //   path: '/setmeal',
  //   name: '套餐管理',
  //   access: '/ticket/combo',
  //   icon: 'ShoppingOutlined',
  //   component: './setmeal',
  // },
  {
    path: '/message',
    name: '消息中心',
    icon: 'ContainerOutlined',
    access: '/ticket/message',
    component: './system/message',
  },
  {
    path: '/record',
    name: '记录管理',
    access: '/ticket/log',
    icon: 'AlignCenterOutlined',
    routes: [
      {
        path: '/record/identification',
        name: '识别记录',
        icon: 'smile',
        access: '/ticket/log/scan',
        component: './record/identification',
      },
      {
        path: '/record/recharge',
        name: '充值记录',
        icon: 'smile',
        access: '/ticket/log/recharge',
        component: './record/recharge',
      },
    ],
  },
  {
    path: '/system',
    name: '系统管理',
    access: '/isystem',
    icon: 'SettingOutlined',
    routes: [
      {
        path: '/system/banner',
        name: '图片配置',
        icon: 'smile',
        access: '/ticket/picture',
        component: './system/banner',
      },
      {
        path: '/system/exchangerate',
        name: '汇率设置',
        icon: 'smile',
        access: '/ticket/exchangeRate',
        component: './system/exchangerate',
      },
      {
        path: '/system/department',
        name: '部门管理',
        icon: 'smile',
        access: '/isystem/depart',
        component: './system/department',
      },
      {
        path: '/setmeal',
        name: '套餐管理',
        access: '/ticket/combo',
        icon: 'ShoppingOutlined',
        component: './setmeal',
      },
      {
        path: '/system/account',
        name: '账号管理',
        icon: 'smile',
        access: '/isystem/user',
        component: './system/account',
      },
      // {
      //   path: '/system/tenant',
      //   name: '租户管理',
      //   icon: 'smile',
      //   access: '/ticket/tenant',
      //   component: './system/tenant',
      // },
      {
        path: '/system/rule',
        name: '角色管理',
        icon: 'smile',
        access: '/isystem/roleUserList',
        component: './system/rule',
      },
      {
        path: '/system/rule/edit',
        name: '权限编辑',
        icon: 'user',
        component: './system/rule/edit',
        hideInMenu: true,
      },
      {
        path: '/trial',
        name: '试用账号管理',
        icon: 'ContainerOutlined',
        access: '/ticket/firm',
        component: './trial',
      },
      {
        path: '/system/configuration',
        name: '服务配置',
        icon: 'ContainerOutlined',
        access: '/ticket/configuration',
        component: './system/configuration',
      },
      {
        path: '/system/contractmodel',
        name: '合同模板',
        icon: 'ContainerOutlined',
        access: '/ticket/contract/model',
        component: './system/contractmodel',
      },
    ],
  },
  //子菜单隐藏但必须写在最外层，否则影响登陆首次跳转页面（同时影响tab切页）
  {
    path: '/system/contractmodel',
    name: '合同模板',
    icon: 'ContainerOutlined',
    access: '/ticket/contract/model',
    hideInMenu: true,
    component: './system/contractmodel',
  },
  {
    path: '/system/configuration',
    name: '服务配置',
    icon: 'ContainerOutlined',
    hideInMenu: true,
    access: '/ticket/configuration',
    component: './system/configuration',
  },
  {
    path: '/system/banner',
    name: '图片配置',
    icon: 'smile',
    access: '/ticket/picture',
    hideInMenu: true,
    component: './system/banner',
  },
  {
    path: '/setmeal',
    name: '套餐管理',
    access: '/ticket/combo',
    icon: 'ShoppingOutlined',
    hideInMenu: true,
    component: './setmeal',
  },
  {
    path: '/basic',
    name: '租户企业',
    icon: 'user',
    hideInMenu: true,
    access: '/ticket/tenant/basic',
    component: './customer/basic',
  },
  {
    path: '/system/exchangerate',
    name: '汇率设置',
    icon: 'smile',
    hideInMenu: true,
    access: '/ticket/exchangeRate',
    component: './system/exchangerate',
  },
  {
    path: '/system/tenant',
    name: '租户管理',
    icon: 'smile',
    hideInMenu: true,
    access: '/ticket/tenant',
    component: './system/tenant',
  },
  {
    path: '/record/identification',
    name: '识别记录',
    icon: 'smile',
    access: '/ticket/log/scan',
    hideInMenu: true,
    component: './record/identification',
  },
  {
    path: '/record/recharge',
    name: '充值记录',
    icon: 'smile',
    hideInMenu: true,
    access: '/ticket/log/recharge',
    component: './record/recharge',
  },
  {
    path: '/system/department',
    name: '部门管理',
    icon: 'smile',
    hideInMenu: true,
    access: '/isystem/depart',
    component: './system/department',
  },
  {
    path: '/system/account',
    name: '账号管理',
    icon: 'smile',
    hideInMenu: true,
    access: '/isystem/user',
    component: './system/account',
  },
  {
    path: '/system/rule',
    name: '角色管理',
    hideInMenu: true,
    icon: 'smile',
    access: '/isystem/roleUserList',
    component: './system/rule',
  },
  {
    path: '/changepassword',
    name: '修改密码',
    icon: 'smile',
    hideInMenu: true,
    component: './changepassword',
  },
  {
    path: '/trial',
    name: '试用账号管理',
    icon: 'ContainerOutlined',
    hideInMenu: true,
    access: '/ticket/firm',
    component: './trial',
  },
  // {
  //   path: '/base',
  //   name: '测试基类',
  //   icon: 'crown',
  //   routes: [
  //     {
  //       path: '/base/base0',
  //       name: '操作页面',
  //       icon: 'smile',
  //       component: './base/Page0',
  //     },
  //     {
  //       path: '/base/base1',
  //       name: '列表页面',
  //       icon: 'smile',
  //       component: './base/Page1',
  //     },
  //     {
  //       path: '/base/base2',
  //       name: '编辑页面',
  //       icon: 'smile',
  //       component: './base/Page2',
  //     },
  //     {
  //       path: '/base/base3',
  //       name: '详情页面',
  //       icon: 'smile',
  //       component: './base/Page3',
  //     },
  //   ],
  // },
  // {
  //   path: '/admin',
  //   name: 'admin',
  //   icon: 'crown',
  //   access: 'canAdmin',
  //   component: './Admin',
  //   routes: [
  //     {
  //       path: '/admin/sub-page',
  //       name: 'sub-page',
  //       icon: 'smile',
  //       component: './Welcome',
  //     },
  //     {
  //       component: './404',
  //     },
  //   ],
  // },
  // {
  //   name: 'list.table-list',
  //   icon: 'table',
  //   path: '/list',
  //   component: './TableList',
  // },
  //默认路径
  // {
  //   path: '/',
  //   redirect: {
  //     path: '/welcome',
  //     // query: { id: document.location.toString().split('?')[1].split('=')[1] },
  //   },
  // },
  // {
  //   path: '/?id=',
  //   forward: '/welcome',
  // },
  {
    path: '/',
    redirect: '/welcome',
    // window.location.search.toString().split('=')[1],?id=${window.location.search.toString().split('=')[1]}
  },
  {
    component: './404',
  },
];
